[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "yarn build"
  publish="build"

[context.develop.environment]
  REACT_APP_CUSTOM_VAR = "development"

[context.deploy-preview.environment]
  REACT_APP_CUSTOM_VAR = "development"

[context.master.environment]
  REACT_APP_CUSTOM_VAR = "production"